# Generated by Django 4.2.7 on 2023-11-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_ambulance_ambulance_location_ambulance_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='telephone_number',
            field=models.CharField(default='Not Provided!', max_length=20),
        ),
    ]
