# Generated by Django 4.2.7 on 2023-11-18 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_ambulance_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
