# Generated by Django 4.2.7 on 2023-11-18 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_remove_ambulance_driver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulance',
            name='driver_name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
