# Generated by Django 4.2.7 on 2023-11-18 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_ambulance_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver_name',
            field=models.CharField(default='1', max_length=20),
        ),
    ]
