# Generated by Django 4.2.7 on 2023-11-18 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_ambulance_driver_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='driver_name',
            field=models.CharField(default='Not Provided!', max_length=100),
        ),
    ]
