# Generated by Django 4.2.7 on 2023-11-18 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_ambulance_driver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ambulance',
            name='telephone_number',
            field=models.CharField(default='Not Provided!', max_length=20, null=True),
        ),
    ]
